/*
* Lab_2.asm
* Creado:		7/02/26
* Autor:		Javier Medina - 22124
* Descripcion: LABORATORIO 1 - SUMADOR
*/

.include "M328PDEF.inc"

.dseg
.org SRAM_START

.cseg
.org 0x0000

//================ STACK =================
	LDI		R16, LOW(RAMEND)
	OUT		SPL, R16
	LDI		R16, HIGH(RAMEND)
	OUT		SPH, R16

//================ SETUP =================
SETUP:
// CONFIG. PRESCALER
    LDI R16, (1 << CLKPCE)
	STS CLKPR, R16				// HABILITAR PRESCALER
	LDI R16, (1 << CLKPS2) 
	STS CLKPR, R16				// PRESCALER A 16 F_cpu = 1MHz

// BOTONES
	CBI		DDRD, PD2		// BOTON INC. CONTADOR 1
	CBI		DDRD, PD3		// BOTON DEC. CONTADOR 1
	CBI		DDRD, PD4		// BOTON INC. CONTADOR 2
	CBI		DDRD, PD5		// BOTON DEC. CONTADOR 2
	CBI		DDRD, PD6		// BOTON SUMA

// PULL-UPS BOTONES
	SBI		PORTD, PD2
	SBI		PORTD, PD3
	SBI		PORTD, PD4
	SBI		PORTD, PD5
	SBI		PORTD, PD6

// CONTADOR 1
	SBI		DDRB, PB0		// LED 1
	SBI		DDRB, PB1		// LED 2
	SBI		DDRB, PB2		// LED 3
	SBI		DDRB, PB3		// LED 4

// CONTADOR 2
	SBI		DDRC, PC0		// LED 1
	SBI		DDRC, PC1		// LED 2
	SBI		DDRC, PC2
	SBI		DDRC, PC3

// RESULTADO
	SBI		DDRD, PD7      // LED 1
	SBI		DDRB, PB4      // LED 2
	SBI		DDRB, PB5      // LED 3
	SBI		DDRC, PC4      // LED 4

// OVERFLOW
	SBI		DDRC, PC5	   // LED OVERFLOW

	LDI		R17, 0x00
	LDI		R20, 0x00

	OUT		PORTB, R17
	OUT		PORTC, R20

RJMP MAIN_LOOP

//================ LOOP =================
MAIN_LOOP:

// CONTADOR 1
	SBIS	PIND, PD2		// INCREMENTO
	RCALL	INC1

	SBIS	PIND, PD3		// DECREMENTO
	RCALL	DEC1

// CONTADOR 2
	SBIS	PIND, PD4		// INCREMENTO
	RCALL	INC2

	SBIS	PIND, PD5		// DECREMENTO
	RCALL	DEC2

// SUMA
	SBIS	PIND, PD6		// SUMA CONTADORES
	RCALL	SUMA

RJMP MAIN_LOOP

//================ CONTADOR 1 =================
// INCREMENTAR
INC1:
	RCALL	DELAY
	SBIS	PIND, PD2
	RET
	INC		R17
	ANDI	R17, 0x0F
	OUT		PORTB, R17

ESPERAR1:
	SBIS	PIND, PD2
	RJMP	ESPERAR1
	RET

// DECREMENTAR
DEC1:
	RCALL	DELAY
	SBIS	PIND, PD3
	RET
	DEC		R17
	ANDI	R17, 0x0F
	OUT		PORTB, R17

ESPERAR2:
	SBIS	PIND, PD3
	RJMP	ESPERAR2
RET

//================ CONTADOR 2 =================
// INCREMENTAR
INC2:
	RCALL	DELAY
	SBIS	PIND, PD4
	RET
	INC		R20
	ANDI	R20, 0x0F
	OUT		PORTC, R20

ESPERAR3:
	SBIS	PIND, PD4
	RJMP	ESPERAR3
RET

// DECREMENTAR
DEC2:
	RCALL	DELAY
	SBIS	PIND, PD5
	RET
	DEC		R20
	ANDI	R20, 0x0F
	OUT		PORTC, R20

ESPERAR4:
	SBIS	PIND, PD5
	RJMP	ESPERAR4
RET

//================ SUMA =================
SUMA:
    RCALL DELAY
    SBIS PIND, PD6
    RET

    MOV R21, R17
    ADD R21, R20

    // OVERFLOW
    BRCC NO_OVERFLOW
    SBI PORTC, PC5
    RJMP MOSTRAR

NO_OVERFLOW:
    CBI PORTC, PC5

MOSTRAR:
    ANDI R21, 0x0F

    // LIMPIAR RESULTADO
    CBI PORTD, PD7
    CBI PORTB, PB4
    CBI PORTB, PB5
    CBI PORTC, PC4

    // BIT 0
    SBRS R21, 0
    RJMP SALTAR0
    SBI PORTD, PD7
SALTAR0:

    // BIT 1
    SBRS R21, 1
    RJMP SALTAR1
    SBI PORTB, PB4
SALTAR1:

    // BIT 2
    SBRS R21, 2
    RJMP SALTAR2
    SBI PORTB, PB5
SALTAR2:

    // BIT 3
    SBRS R21, 3
    RJMP SALTAR3
    SBI PORTC, PC4
SALTAR3:

ESPERAR_SUMA:
    SBIS PIND, PD6
    RJMP ESPERAR_SUMA

    RET
//================ DELAY =================
DELAY:
	LDI		R18, 150
D1:
	LDI		R19, 255
D2:
	DEC		R19
	BRNE	D2
	DEC		R18
	BRNE	D1
	RET
