
/*
* PROYECTO_1_JAVIER_MEDINA.asm
*
* Creado: 20/02/2026
* Autor : JAVIER MEDINA - 22124
* Descripción: PROYECTO 1: RELOJ
*/
//=========================================================

.include "M328PDEF.inc"

//=========================================================
// VECTORES DE INTERRUPCIÓN
//=========================================================
.cseg
.org 0x0000
RJMP MAIN              

.org 0x001A
RJMP TIMER1_ISR        // INTERRUPCION TIMER1 (1 segundo)

.org 0x0020
RJMP TIMER0_ISR        // INTERRUPCION TIMER0 (MULTIPLEX & LEDS RELOJ)

//=========================================================
// PROGRAMA PRINCIPAL
//=========================================================
MAIN:
LDI		R16, LOW(RAMEND)
OUT		SPL, R16
LDI		R16, HIGH(RAMEND)
OUT		SPH, R16

// CONFIG. PUERTOS
	//	PUERTO D (SEGMENTOS A-F)
LDI		R16, 0b11111100
OUT		DDRD, R16

	// PUERTO B (MULTIPLEX & SEGMENTO G)
LDI		R16, 0b00011111
OUT		DDRB, R16

CLR		R16
OUT		PORTB, R16          // DISPLAYS APAGADAS AL INICIO

// CONFIG. BOTONES
CBI		DDRC, PC0			// BOTON CAMBIO MODO
CBI		DDRC, PC1			// BOTON +
CBI		DDRC, PC2			// BOTON -

	// PULL-UP BOTONES
SBI		PORTC, 0
SBI		PORTC, 1
SBI		PORTC, 2

// CONFIG. LEDS
SBI		DDRC, PC3			// LED RELOJ 1
SBI		DDRC, PC4			// LED RELOJ 2
SBI		DDRC, PC5			// LED MODO RELOJ (NORMAL & CAMBIOS)
SBI		DDRB, PB5			// LED MODO CALENDARIO (NORMAL & CAMBIOS)

//TABLA 7 SEG.
TABLA:
.DB 0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F

//=========================================================
// CONFIGURACIÓN TIMER0 (MULTIPLEX)
//=========================================================
CLR		R16
OUT		TCCR0A, R16               // MODO NORMAL

LDI		R16, (1 << CS02) | (1 << CS00)  // PRESCALER 1024
OUT		TCCR0B, R16

LDI		R16, 200                
OUT		TCNT0, R16

LDI		R16, (1 << TOIE0)           // INTERRUPCION
STS		TIMSK0, R16

//=========================================================
// CONFIGURACIÓN TIMER1 (1 SEGUNDO)
//=========================================================
CLR		R16
STS		TCCR1A, R16

LDI		R16, (1 << CS12) | ( 1 << CS10)  // PRESCALER 1024
STS		TCCR1B, R16

// RECARGA CALCULADA PARA CONTAR 1s (EN 16 MHz)
LDI		R16, 0xC2
STS		TCNT1H, R16
LDI		R16, 0xF7
STS		TCNT1L, R16

LDI		R16, (1 << TOIE1)
STS		TIMSK1, R16

//=========================================================
// LIMPIEZA REGISTROS
//=========================================================
CLR		R17   // SEGUNDOS
CLR		R18   // MINUTOS & MESES (UNIDAD)
CLR		R19   // MINUTOS & MESES (DECENA)
CLR		R20	  // HORA & DIAS (UNIDAD)
CLR		R21   // HORA & DIAS (UNIDAD)
CLR		R22   // DISPLAY ACTIVO
CLR		R23   // MODO ACTUAL
CLR		R28   // CONTADOR TICKS (MODO RELOJ)
CLR		R27   // toggle LED 

SEI       

// =========================================================
// LOOP PRINCIPAL
// =========================================================
MAIN_LOOP:

IN		R24, PINC              // SE LEE ESTADO DE BOTONES

SBRS	R24, 0             
RCALL	CAMBIAR_MODO

// MODO ACTUAL
CPI		R23, 0
BREQ	MODO_RELOJ				// MODO RELOJ

CPI		R23, 1					// MODO AJUSTE HORA
BREQ	MODO_HORA

CPI		R23, 2					// MODO AJUSTE MINUTOS
BREQ	MODO_MIN

CPI		R23, 3					// MODO CALENDARIO
BREQ	MODO_CAL

CPI		R23, 4					// MODO AJUSTE MESES
BREQ	MODO_MESES

CPI		R23, 5					// MODO AJUSTE DIAS
BREQ	MODO_DIAS

RJMP	MAIN_LOOP              // REGRESA A MODO RELOJ

	// MODO RELOJ
MODO_RELOJ:
SBI		PORTC, PC5      // LED ENCENDIDO (MODO RELOJ)
CBI		PORTB, PB5     // LED APAGADO

RJMP	MAIN_LOOP

	// MODO AJUSTE HORAS
MODO_HORA:
SBI		PORTC, PC5      // LED ENCENDIDO (MODO RELOJ)
CBI		PORTB, PB5      // LED APAGADO
SBRS	R24, 1			// BOTON +
RCALL	INC_HORA
SBRS	R24, 2			// BOTON -
RCALL	DEC_HORA

RJMP MAIN_LOOP


	// MODO AJUSTE MINUTOS
MODO_MIN:
SBI		PORTC, PC5      // LED ENCENDIDO (MODO RELOJ)
CBI		PORTB, PB5      // LED APAGADO
SBRS	R24, 1			// BOTON +
RCALL	INC_MIN
SBRS	R24, 2			// BOTON -
RCALL	DEC_MIN

RJMP MAIN_LOOP

	// MODO CALENDARIO
MODO_CAL:
SBI		PORTB, PB5      // LED ENCENDIDO (MODO CALENDARIO)
SBI		PORTC, PC3		// LED ENCENDIDO
SBI		PORTC, PC4		// LED ENCENDIDO
CBI		PORTC, PC5		// LED APAGADO

RJMP	MAIN_LOOP

	// MODO AJUSTE DIAS
MODO_DIAS:
SBI		PORTB, PB5      // LED ENCENDIDO (MODO CALENDARIO)
CBI		PORTC, PC5     // LED APAGADO
SBRS	R24, 1		   // BOTON +
RCALL	INC_DIAS
SBRS	R24, 2		   // BOTON -
RCALL	DEC_DIAS

RJMP	MAIN_LOOP

	// MODO AJUSTE MESES
MODO_MESES:
SBI		PORTB, PB5      // LED ENCENDIDO (MODO CALENDARIO)
CBI		PORTC, PC5     // LED APAGADO
SBRS	R24, 1		   // BOTON +
RCALL	INC_MESES
SBRS	R24, 2		  // BOTON -
RCALL	DEC_MESES

RJMP MAIN_LOOP

//=========================================================
// MOSTRAR EN DISPLAYS
//=========================================================
MOSTRAR:

LDI		ZH, HIGH (TABLA << 1)
LDI		ZL, LOW (TABLA << 1)
ADD		ZL, R16
LPM		R16, Z

// SEGMENTOS A-F
MOV		R15, R16
LSL		R15
LSL		R15
OUT		PORTD, R15

// SEGMENTO G
CBI		PORTB, 4
SBRC	R16, 6
SBI		PORTB, 4

RET

//=========================================================
// SUBRUTINAS BOTONES
//=========================================================

// CAMBIO MODOS
CAMBIAR_MODO:
RCALL	DELAY

ESPERA0:
SBIS	PINC,0
RJMP	ESPERA0

INC		R23				// CAMBIA MODO
CPI		R23, 6
BRLO	REVISAR_MODO
CLR		R23		

REVISAR_MODO:
	// MODO CALENDARIO
CPI		R23, 3
BRNE	REVISAR_SALIDA

	// SE GUARDA LA HORA DEL RELOJ
MOV		R12, R18
MOV		R13, R19
MOV		R14, R20
MOV		R15, R21

	// INICIALIZAR FECHA XX/XX
LDI		R18, 3 
CLR		R19
LDI		R20, 0
LDI		R21, 2

RJMP FIN_CAMBIO


	// REGRESO A MODO RELOJ
REVISAR_SALIDA:
CPI		R23, 0
BRNE	FIN_CAMBIO

	// RESTAURAR HORA
MOV		R18, R12
MOV		R19, R13
MOV		R20, R14
MOV		R21, R15

	//ESPERAR QUE SUELTE BOTON
ESPERA_LIBERAR:
SBIS	PINC, 0        
RJMP	ESPERA_LIBERAR
RCALL	DELAY        

FIN_CAMBIO:
RET

// RELOJ
	// HORA (INCREMENTO & DECREMENTO)
		// INCREMENTO HORAS
INC_HORA:
RCALL	DELAY

ESPERA1:
SBIS	PINC, 1
RJMP	ESPERA1

INC		R20
CPI		R21, 2
BRNE	INC_NORMAL_HORA
CPI		R20, 4
BRLO	REINICIO_INC_HORA
CLR		R20
CLR		R21
RET

INC_NORMAL_HORA:
CPI		R20, 10
BRLO	REINICIO_INC_HORA
CLR		R20
INC		R21
CPI		R21, 3
BRLO	REINICIO_INC_HORA
CLR		R21

REINICIO_INC_HORA:
RET

		// DECREMENTO HORAS
DEC_HORA:
RCALL	DELAY

ESPERA2:
SBIS	PINC, 2
RJMP	ESPERA2

CPI		R21, 0
BRNE	DEC_HORA1
CPI		R20, 0
BRNE	DEC_HORA1
LDI		R21, 2
LDI		R20, 3
RET

DEC_HORA1:			// DECREMENTO CUANDO UNIDAD = 0
CPI		R20, 0
BRNE	DEC_HORA2
DEC		R21
LDI		R20, 9
RET

DEC_HORA2:			// DECREMENTO NORMAL
DEC		R20
RET

	// MINUTOS (INCREMENTO & DECREMENTO)
		// INCREMENTO MINUTOS
INC_MIN:
RCALL	DELAY

ESPERA3:
SBIS	PINC, 1
RJMP	ESPERA3

INC		R18			// INCREMENTO UNIDADES
CPI		R18, 10
BRLO	REINICIO_INC_MIN
CLR		R18
INC		R19			// AL SER 10, SE INCREMENTA EN DECENA
CPI		R19, 6
BRLO	REINICIO_INC_MIN
CLR		R19

REINICIO_INC_MIN:
RET

		// DECREMENTO MINUTOS
DEC_MIN:
RCALL	DELAY

ESPERA4:
SBIS	PINC, 2
RJMP	ESPERA4

CPI		R19, 0
BRNE	DEC_MIN1
CPI		R18, 0
BRNE	DEC_MIN1
LDI		R19, 5
LDI		R18, 9
RET

DEC_MIN1:			// DECREMENTO CUANDO UNIDAD = 0
CPI		R18, 0
BRNE	DEC_MIN2
DEC		R19
LDI		R18, 9
RET

DEC_MIN2:			// DECREMENTO NORMAL
DEC		R18
RET

// CALENDARIO
	// MESES (INCREMENTO & DECREMENTO)
		// INCREMENTO MESES
INC_MESES:
RCALL	DELAY

ESPERA5:
SBIS	PINC, 1
RJMP	ESPERA5

INC		R18              // INCREMENTA UNIDAD
CPI		R18, 10
BRLO	REVISAR_MAX_MES
CLR		R18
INC		R19              // INCREMENTA DECENA

REVISAR_MAX_MES:

// VERIFICA SI MAX = 12
CPI		R19, 1
BRNE	FIN_INC_MES
CPI		R18, 3
BRLO	FIN_INC_MES

CLR		R19				// AL PASAR DE 12 MESES, VUELVE A 01
LDI		R18, 1

FIN_INC_MES:
RET

		// DECREMENTO MESES
DEC_MESES:
RCALL	DELAY

ESPERA6:
SBIS	PINC, 2
RJMP	ESPERA6

// VERIFICIA SI MIN = 01
CPI		R19, 0
BRNE	NO_01_MES
CPI		R18, 1
BRNE	NO_01_MES

LDI		R19, 1
LDI		R18, 2			// AL BAJAR DE 01 MESES, VUELVE A 12
RET

NO_01_MES:				// DECREMENTO NORMAL
CPI		R18, 0
BRNE	DEC_UNIDAD_MES
DEC		R19
LDI		R18, 9
RET

DEC_UNIDAD_MES:
DEC		R18
RET

	// DIAS (INCREMENTO & DECREMENTO)
		// INCREMENTO DIAS
INC_DIAS:
RCALL	DELAY

ESPERA7:
SBIS	PINC, 1
RJMP	ESPERA7

INC		R20              // INCREMENTA UNIDAD
CPI		R20, 10
BRLO	VALIDAR_MES_INC
CLR		R20
INC		R21              // INCREMENTA DECENA


		// VALIDACION POR MES
			// MES DE FEBRERO 
VALIDAR_MES_INC:
CPI		R19, 0			// REVISA SI MES (DECENA) = 0
BRNE	VALIDAR_MES_30_INC     
CPI		R18,2			// REVISA SI MES (UNIDAD) = 2
BRNE	VALIDAR_MES_30_INC

			// MAXIMO 28 DIAS
LIMITE_28:
CPI		R21, 2
BRLO	FIN_INC_DIAS
BRNE	RESET_DIA
CPI		R20, 9
BRLO	FIN_INC_DIAS

RJMP RESET_DIA

			// MESES DE 30 DIAS (04, 06, 09, 11)
VALIDAR_MES_30_INC:
			// ABRIL
VALIDAR_04_INC:
CPI		R19, 0
BRNE	VALIDAR_06_INC
CPI		R18, 4
BREQ	LIMITE_30_INC

			// JUNIO
VALIDAR_06_INC:
CPI		R19, 0
BRNE	VALIDAR_09_INC
CPI		R18, 6
BREQ	LIMITE_30_INC

			// SEPTIEMBRE
VALIDAR_09_INC:
CPI		R19, 0
BRNE	VALIDAR_11_INC
CPI		R18, 9
BREQ	LIMITE_30_INC

			// NOVIEMBRE
VALIDAR_11_INC:
CPI		R19, 1
BRNE	LIMITE_31_INC
CPI		R18, 1
BREQ	LIMITE_30_INC

				// LIMITAR A 30 DIAS ESTOS MESES
LIMITE_30_INC:
CPI		R21, 3
BRLO	FIN_INC_DIAS
BRNE	RESET_DIA
CPI		R20, 1
BRLO	FIN_INC_DIAS

RJMP RESET_DIA


			// MESES DE 31 DIAS (MODO NORMAL)
LIMITE_31_INC:
CPI		R21, 3
BRLO	FIN_INC_DIAS
BRNE	RESET_DIA
CPI		R20, 2
BRLO	FIN_INC_DIAS
RJMP	RESET_DIA

			// RESET DIAS
RESET_DIA:
CLR		R21
LDI		R20, 1			// REGRESAN A 01 DIAS

FIN_INC_DIAS:
RET

		// DECREMENTO DIAS
DEC_DIAS:
RCALL DELAY

ESPERA8:
SBIS	PINC, 2
RJMP	ESPERA8

			// SI NO ES 01, RESTA NORMAL
CPI		R21, 0
BRNE	DEC_DIAS_NORMAL
CPI		R20, 1
BRNE	DEC_DIAS_NORMAL

			// AL SER 01, REGRESA AL UTLIMO DIA DEL MES
				// FEBRERO
CPI		R19, 0
BRNE	VALIDAR_MES_30_DEC
CPI		R18, 2
BRNE	VALIDAR_MES_30_DEC
LDI		R21, 2
LDI		R20, 8
RET

			// MESES DE 30 DIAS (04, 06, 09, 11)
VALIDAR_MES_30_DEC:
			// ABRIL
VALIDAR_04_DEC:
CPI		R19, 0
BRNE	VALIDAR_06_DEC
CPI		R18, 4
BREQ	LIMITE_30_DEC

			// JUNIO
VALIDAR_06_DEC:
CPI		R19, 0
BRNE	VALIDAR_09_DEC
CPI		R18, 6
BREQ	LIMITE_30_DEC

			// SEPTIEMBRE
VALIDAR_09_DEC:
CPI		R19, 0
BRNE	VALIDAR_11_DEC
CPI		R18, 9
BREQ	LIMITE_30_DEC

			// NOVIEMBRE
VALIDAR_11_DEC:
CPI		R19, 1
BRNE	LIMITE_31_DEC
CPI		R18, 1
BREQ	LIMITE_30_DEC

				// LIMITAR A 30 DIAS ESTOS MESES
LIMITE_30_DEC:
LDI		R21, 3
LDI		R20, 0
RET

			// MESES RESTANTES (31 DIAS)
LIMITE_31_DEC:
LDI		R21, 3
LDI		R20, 1
RET

		// DECREMENTO NORMAL 
DEC_DIAS_NORMAL:
CPI		R20, 0
BRNE	DEC_DIAS_UNIDAD
DEC		R21
LDI		R20, 9
RET

DEC_DIAS_UNIDAD:
DEC		R20
RET

//=========================================================
// INTERRUPCIÓN TIMER0 (MULTIPLEXADO & LEDS RELOJ)
//=========================================================
TIMER0_ISR:

PUSH    R15
PUSH	R16
PUSH	R24

// RECARGA PARA MULTIPLEX
LDI		R16, 200
OUT		TCNT0, R16           

INC		R22
CPI		R22, 4
BRLO	DISPLAYS
CLR		R22

DISPLAYS:
CPI		R22, 0
BREQ	DISPLAY_1
CPI		R22, 1
BREQ	DISPLAY_2
CPI		R22, 2
BREQ	DISPLAY_3
RJMP	DISPLAY_4

DISPLAY_1:
MOV		R16, R18              // MINUTOS (UNIDADES)
RCALL	MOSTRAR
LDI		R24, (1 << 0)
RJMP	ACTIVAR_DISP

DISPLAY_2:
MOV		R16, R19              // MINUTOS (DECENAS)
RCALL	MOSTRAR
LDI		R24, (1 << 1)
RJMP	ACTIVAR_DISP

DISPLAY_3:
MOV		R16, R20              // HORAS (UNIDADES)
RCALL	MOSTRAR
LDI		R24, (1 << 2)
RJMP	ACTIVAR_DISP

DISPLAY_4:
MOV		R16, R21              // HORAS (DECENAS)
RCALL	MOSTRAR
LDI		R24,(1 << 3)

ACTIVAR_DISP:
IN		R16, PORTB
ANDI	R16, 0b11110000		// APAGA TODOS
OR		R16, R24			// ENCIENDE SOLO 1
OUT		PORTB, R16

// 500ms LEDs PARPADEO MODO RELOJ
INC		R28
CPI		R28, 140			// PARA QUE SEAN 500ms (140 INTERRUPCIONES x 3.54ms = 500 ms)
BRLO	SALIDA_TIMER0
CLR		R28

	// TOGGLE LEDs
LDI		R16, 1
EOR		R27, R16		// XOR PARA ALTERNAR

CPI		R23, 0			// SOLO FUNCIONA EN R23 = 0 (MODO RELOJ)
BRNE	PARPADEO_OFF
CPI		R27, 1
BREQ	PARPADEO_ON
CBI		PORTC, PC3
CBI		PORTC, PC4
RJMP	SALIDA_TIMER0

PARPADEO_ON:
SBI		PORTC, PC3
SBI		PORTC, PC4
RJMP	SALIDA_TIMER0

PARPADEO_OFF:
CBI		PORTC, PC3
CBI		PORTC, PC4

SALIDA_TIMER0:
POP		R15
POP		R16
POP		R24
RETI

//=========================================================
// INTERRUPCIÓN TIMER1
//=========================================================
TIMER1_ISR:

PUSH	R16

// SOLO CUENTA EN MODO RELOJ
CPI		R23, 0
BRNE	SALIDA_TIMER1

// SE VUELVE A RECARGAR PARA 1s
LDI		R16, 0xC2
STS		TCNT1H, R16
LDI		R16, 0xF7
STS		TCNT1L, R16

// INCREMENTO SEGUNDOS
INC		R17
CPI		R17, 1				// ESTA EN 1 PARA QUE INCREMENTE CADA SEG. (NORMALMENTE EN 60)
BRLO	SALIDA_TIMER1
CLR		R17

// INCREMENTO MINUTOS
	// MINUTOS (UNIDAD)
INC		R18
CPI		R18, 10			// SOLO INCREMENTA DE 0-9 MIN (UNIDADES)
BRLO	SALIDA_TIMER1
CLR		R18

// MINUTOS (DECENAS)
INC		R19
CPI		R19, 6			// SOLO INCREMENTA DE 0-5 MIN (DECENAS)
BRLO	SALIDA_TIMER1
CLR		R19

// INCREMENTO HORAS
INC		R20

// FORMATO 24 HORAS
CPI		R21, 2
BRNE	NORMAL_HORAS

CPI		R20, 4
BRLO	SALIDA_TIMER1
CLR		R20
CLR		R21
RJMP	SALIDA_TIMER1

NORMAL_HORAS:
CPI		R20, 10
BRLO	SALIDA_TIMER1
CLR		R20
INC		R21
CPI		R21, 3
BRLO	SALIDA_TIMER1
CLR		R21


SALIDA_TIMER1:
POP		R16
RETI

//=========================================================
// DELAY
//=========================================================
DELAY:
LDI		R25, 255
D1:
DEC		R25
BRNE	D1
RET
